# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 09:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20171226_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 26, 17, 5, 21, 933929), verbose_name='添加时间'),
        ),
    ]
