# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-31 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20171226_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 31, 15, 45, 57, 498927), verbose_name='添加时间'),
        ),
    ]
