# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-01 15:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20171231_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 1, 15, 28, 55, 754992), verbose_name='添加时间'),
        ),
    ]
